# Generated by Django 2.0.1 on 2018-01-05 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Community')),
            ],
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=20)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Community')),
            ],
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Matching')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woman_score', models.IntegerField()),
                ('man_score', models.IntegerField()),
                ('man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Man')),
            ],
        ),
        migrations.CreateModel(
            name='Woman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Community')),
                ('pairing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Pairing')),
            ],
        ),
        migrations.AddField(
            model_name='ranking',
            name='woman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Woman'),
        ),
        migrations.AddField(
            model_name='man',
            name='pairing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Pairing'),
        ),
    ]
