# Generated by Django 2.0.1 on 2018-01-05 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='number_couples',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
