# Generated by Django 2.0.1 on 2018-01-08 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20180105_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man',
            name='pairing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Pairing'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='pairing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Pairing'),
        ),
    ]
