# Generated by Django 2.0.1 on 2018-01-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20180108_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
