# Generated by Django 2.0.1 on 2018-01-09 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('match', '0004_auto_20180109_0205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Man',
            new_name='Blue',
        ),
        migrations.RenameModel(
            old_name='Woman',
            new_name='Red',
        ),
        migrations.RenameField(
            model_name='ranking',
            old_name='man_score',
            new_name='blue_score',
        ),
        migrations.RenameField(
            model_name='ranking',
            old_name='woman',
            new_name='red',
        ),
        migrations.RenameField(
            model_name='ranking',
            old_name='woman_score',
            new_name='red_score',
        ),
        migrations.RenameField(
            model_name='ranking',
            old_name='man',
            new_name='blue',
        ),
        migrations.AlterUniqueTogether(
            name='blue',
            unique_together={('community', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='red',
            unique_together={('community', 'name')},
        ),
    ]
