# Generated by Django 2.0.1 on 2018-01-11 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_auto_20180109_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='blue_score',
            new_name='blue_to_red_score',
        ),
        migrations.RenameField(
            model_name='ranking',
            old_name='red_score',
            new_name='red_to_blue_score',
        ),
    ]
