# Generated by Django 2.0.1 on 2018-01-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_auto_20180111_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='blue_to_red_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='red_to_blue_score',
            field=models.IntegerField(null=True),
        ),
    ]
