# Generated by Django 2.0.1 on 2018-01-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_auto_20180112_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='algorithm',
            field=models.CharField(choices=[('SGBP', 'Shapley Gale Blue Propose'), ('SGRP', 'Shapley Gale Red Propose')], default='SGBP', max_length=10),
        ),
    ]
