# Generated by Django 2.0.1 on 2018-01-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_auto_20180112_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='number_couples',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='matching',
            unique_together={('community', 'algorithm')},
        ),
    ]
