# Generated by Django 2.0.1 on 2018-01-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_auto_20180121_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='blue_to_red_score',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='red_to_blue_score',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
