# Generated by Django 2.0.1 on 2018-01-22 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0012_auto_20180122_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blue',
            name='pairing',
        ),
        migrations.RemoveField(
            model_name='red',
            name='pairing',
        ),
        migrations.AddField(
            model_name='pairing',
            name='blue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='match.Blue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pairing',
            name='red',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='match.Red'),
            preserve_default=False,
        ),
    ]
